apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-deployment
  labels:
    app: flask_test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask_test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: flask_test
    spec:
      containers:
      - name: simple-flask
        # image: IMAGE_TAG
        image: tomjab/flask_test
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
